spring:
  application:
    name: exe101-workflow
  profiles:
    active: local

server:
  port: 8082
  shutdown: graceful
  undertow:
    accesslog:
      enabled: ${UNDERTOW_ACCESSLOG_ENABLED:false}
      pattern: ${UNDERTOW_ACCESSLOG_PATTERN:%h %l %u %t \"%r\" %s %b}
    threads:
      io: ${UNDERTOW_IO_THREADS:4}
      worker: ${UNDERTOW_WORKER_THREADS:32}
    max-http-post-size: ${UNDERTOW_MAX_HTTP_POST_SIZE:10485760}