spring:
  config:
    activate-on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: INFO
