spring:
  application:
    name: exe101-cronjob
  profiles:
    active: local

server:
  port: 8084
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
