spring:
  application:
    name: workflow
  config:
    import: optional:classpath:application.yaml
  
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: 8082
