spring:
  config:
    activate:
      on-profile: stage
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:stage-db.example.com}:${DB_PORT:5432}/read
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8083

