spring:
  config:
    activate:
      on-profile: stage
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:stage-db.example.com}:${DB_PORT:5432}/cronjob
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  cloud:
    task:
      execution:
        pool:
          core-size: 3
          max-size: 15

server:
  port: 8085

logging:
  level:
    org.springframework.scheduling: WARN

