spring:
  application:
    name: authen
  config:
    import: optional:classpath:application.yaml
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
