spring:
  application:
    name: email
  config:
    import: optional:classpath:application.yaml
  
  datasource:
    url: jdbc:postgresql://localhost:5432/email
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084
